language: android
before_install: #1.1
- nvm install 11.15.0
- node --version
install: #1.2
- npm install
android: #1.3
  components:
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script: 
- npm test #2
- cd android && ./gradlew assembleRelease #3
after_success:
  - bash <(curl -s https://codecov.io/bash)